### ISSUE TITLE
HR doesn't change

### ISSUE THREAD

**Issue by admiralamott1** [qe201020335/HRCounter#1]
Hey,
I love this idea but I'm having problems with it. I have it all set up in game, and it displays as a counter, but it only displays 1 number that i assume is what it found on launch and doesnt change. I.e. One launch it only displayed "119", played several songs and it didn't change, another launch it was 107, played several songs and it didn't change, etc. 
Really looking forward to using this properly so thanks for any help :)

**Comment by qe201020335** [comment]
Thanks for your reporting. 
Could you provide a log file, it is in Beat Saber/Logs/HRCounter. 
Also, which version of the game are you running with?
