### ISSUE TITLE
Mi Band 6 support?

### ISSUE THREAD

**Issue by limerrrr** [qe201020335/HRCounter#11]
I was wondering if it would be possible to get this mod to work with the Mi Band 6

**Comment by qe201020335** [comment]
If you have an iPhone, HypeRate has the support for Mi Bands, you can try that.
Also. I think Mi Bands are BLE compatible, so you can try to enable that and use Pulsoid with it.

**Comment by limerrrr** [comment]
ok thanks I'll try to use it with Pulsoid

**Comment by limerrrr** [comment]
works btw
