### ISSUE TITLE
Support for Xiaomi Mi Watch

### ISSUE THREAD

**Issue by xCloudburst** [qe201020335/HRCounter#15]
Hiya,

I can't seem to find a way to push any data out of my Mi Watch (Model: XMWTCL02).

I'd love it if this supported a form of software that is able to do this as the watch's default is "Xiaomi Wear".

Would be more than happy to help with any testing too!

**Comment by qe201020335** [comment]
Hi there,
after some research, it seems that there isn't an public api for getting realtime heart rate data.
Unfortunately, I can't support it. 

I'm going to close this issue for now. Feel free to reopen this issue if you find anything and please leave a link. Thanks!

**Comment by 200Tigersbloxed** [comment]
Apparently, Pulsoid already support Xaomi Mi Watches, fyi https://www.blog.pulsoid.net/post/how-to-use-xiaomi-mi-band-3-with-android-pulsoid-app

**Comment by qe201020335** [comment]
> Apparently, Pulsoid already support Xaomi Mi Watches, fyi https://www.blog.pulsoid.net/post/how-to-use-xiaomi-mi-band-3-with-android-pulsoid-app

Yeah, but it is for mi bands. Mi Bands are BLE compatible. However, Mi Watch is not. 😞
