### ISSUE TITLE
Add YUR support

### ISSUE THREAD

**Issue by qe201020335** [qe201020335/HRCounter#17]
Display real / estimated heart rate by stealing data from YUR mod. :D

**Comment by GigaFyde** [comment]
Or perhaps also push to YUR if there's an incoming Pulsoid stream?

**Comment by qe201020335** [comment]
As much as I want to do this, it is not very practical. YUR handles real hr data only in their dedicated software. I have to also "mod" it to inject heart rate data.

When you launch Beat Saber while having their dedicated software running, the mod is basically just an in-game display and gathers your in-game level play information.

**Comment by qe201020335** [comment]
Second thought, it might be possible to make a virtual BLE device driver and just pipe the heart rate through the virtual device.

**Comment by Kakifrucht** [comment]
Do you still plan to implement taking the HR data from YUR? Would be awesome!

**Comment by qe201020335** [comment]
@Kakifrucht 
Yes, it is still planned.
I will start working on it after my final exams

**Comment by qe201020335** [comment]
Support for YUR desktop app is here in version v1.5.0.

**Comment by Kakifrucht** [comment]
works perfectly thank you very much!

**Comment by qe201020335** [comment]
Will add YUR mod support in the 2.0 update. Coming very soon!

**Comment by qe201020335** [comment]
YUR mod support added in 4d611340c958e4ca85802e633df3916c8da69b39
