### ISSUE TITLE
HRCounter not showing up in game

### ISSUE THREAD

**Issue by JW6677** [qe201020335/HRCounter#22]
I've downloaded and setup hyperate through testflight on my apple watch. I can go to their website and see my updating heart rate and I've setup the HR counter config file. This is my current config file:
`{
  "LogHR": false,
  "DataSource": "HypeRate",
  "HypeRateSessionID": "4055",
  "PulsoidWidgetID": "NotSet",
  "FitbitWebSocket": "ws://localhost:8080/",
  "FeedLink": "NotSet",
  "Colorize": true,
  "HideDuringReplay": true,
  "HRLow": 120,
  "HRHigh": 180,
  "LowColor": "#00FF00",
  "MidColor": "#FFFF00",
  "HighColor": "#FF0000",
  "PauseHR": 200,
  "AutoPause": true
}`

I've gone into the counter+ config in beat saber and enabled HRCounter and positioned it where I want it however when I get into a song, the hear rate counter just isn't there. Is this to do with the issue of the new hyperate API? Is there a fix?
Github makes my config file look weird so this is a screenshot aswell:
![image](https://user-images.githubusercontent.com/17951453/152387059-0953965b-bba9-47b9-b08b-251d76dc70d9.png)

**Comment by qe201020335** [comment]
Could you upload the log file when this happened? It's in `Beat Saber/Logs`
