### ISSUE TITLE
FPFC disabling/breaking when watching replays with HideDuringReplay set to true

### ISSUE THREAD

**Issue by Kakifrucht** [qe201020335/HRCounter#23]
When launching Beat Saber with FPFC enabled (and Camera2) you lose control over the pointer after watching a replay. This only happens when HideDuringReplay is set to true. I'm on the latest version 1.19.0

My guess is that the issue is caused by invoking this ScoreSaber method here: https://github.com/qe201020335/HRCounter/blob/c7e981be4f7d95a46beba44d4fd9eb7156e6eddd/HRCounter/Utils/Utils.cs#L23

**Comment by qe201020335** [comment]
Are you on game version 1.19.0 with the latest mods?
I do see some `NullReferenceException` throwing around when I press G to reenable FPFC after a replay.

I have fixed it but am not sure whether this is the cause of your problem. 
Do you mind using this test version I just built and see if the problem goes away?
[HRCounter-1.5.0-bs1.19.0-08725ec.zip](https://github.com/qe201020335/HRCounter/files/7998971/HRCounter-1.5.0-bs1.19.0-08725ec.zip)

**Comment by Kakifrucht** [comment]
Yup issue gone with that version, thanks for speedy fix!
