### ISSUE TITLE
HR stuck at 0

### ISSUE THREAD

**Issue by TehSolider** [qe201020335/HRCounter#3]
Hey, really liking the idea of this mod but got a bit of an issue.
It shows up in game fine but always displays 0 for the HR.
I've followed the instructions of dropping the .dll in plugins, running the game, closing the game and pasting my pulsoid feed link into the .json file in userdata.
I've restarted the game and made sure the changes made to the .json stuck, also restarted my PC but it still stays at 0 at all times.
The pulsoid link is correct and in my browser shows a heartrate, it does so too on my phone, also tested it with OBS and it works there too, just not in BS for some reason.
Below is the latest log from Beat Saber/Logs/HRCounter and a screenshot of the config.
[_latest.log](https://github.com/qe201020335/HRCounter/files/6523294/_latest.log)
![grafik](https://user-images.githubusercontent.com/7550068/119156317-689beb00-ba54-11eb-9bf2-30de971cb7f0.png)
I've also removed the "" around the link just in case but that didn't change anything either.

**Comment by qe201020335** [comment]
Hi, upon looking at your config json, the feedlink is wrong. The link you are using is the widget link, not the api feed link. The api feed link is at the bottom of this page. https://pulsoid.net/ui/configuration
The link should start with "https://pulsoid.net/v1/api/feed/..."
Also you should not remove the "" around the link.

**Comment by TehSolider** [comment]
Oh I see, must have confused widget with feed.
Works flawlessly now, thank you very much.
