### ISSUE TITLE
Minimum/maximum tweak?

### ISSUE THREAD

**Issue by xedlock** [qe201020335/HRCounter#30]
Any possibility you can lower the minimum and maximum HR?

I take a beta blocker for anxiety and one of its "features" is it greatly reduces heart rate.  Those of us on them will play and will rarely have a HR over 100 -- but when it does get that high, it's dangerous -- that's like 180 for those not taking beta blockers. ~100's where the game should pause for me, but I can't set it that low. I've been recompiling the mod to change it, but it kind of makes more sense to get that in the code? Minimum is the same - I'm usually at 50-51 when I start playing - but that's not as important. 

I've got lots of records that show a 2 hour session while taking it, I average at 63bpm. Not taking it, 140. 

Anyway, just thought I'd ask. 🙂

**Comment by qe201020335** [comment]
Just to make sure, 
I should make the lower bound for the "auto pause heart rate" silder lower?
https://github.com/qe201020335/HRCounter/blob/8999eaeb88cd749ca7a59ae94b5727e09910cb88/HRCounter/UI/BSML/configMenu.bsml#L30

Basically set the min value to something like 90.

**Comment by qe201020335** [comment]
I should probably lower the higher bound too. There is no way somebody can withstand a heart rate of 220+ for more than a few seconds.

**Comment by xedlock** [comment]
Sorry for being confusing -- I created this issue from my phone while at a bar (I received the release notification and realized I should probably ask about the floor/ceiling change).

I'm not a C# programmer by any stretch -- I'm a linux/mac Python/Ruby engineer so I'm out of my league -- so please forgive my stupidity.  I've been modifying configMenu.bsml (and the CountersPlus bsml before you pulled it out), and I haven't had any side effects yet... but that said.. Since the config menu was preventing it, I'm not sure what will happen if someone raises the lower limit above the upper limit. I'm sure the color generator would get upset about it, though. 

I realize I could just manually edit the JSON config file, but that's kind of a pain once you're already in the game. I purposefully skip the meds on some days, I tend to adjust the min/max/pause a lot (configurable profiles would be kind of nice,  but that seems useless for 99% of people, so it's probably not worth it).

If this is going to make you to add code to check for overlaps and other nonsense, it's probably not worth it.

This is the change I make before rebuilding the plugin... same as what you're doing above.

```
index 3dee70e..20f418d 100644
--- a/HRCounter/UI/BSML/configMenu.bsml
+++ b/HRCounter/UI/BSML/configMenu.bsml
@@ -19,4 +19,4 @@
                 <bool-setting text="Colorize HR Text" value="Colorize" hover-hint="Colorize the heart rate number." apply-on-change="true"/>
-                <slider-setting text="Heart Rate Lower Bound" show-buttons="true" value="HRLow" integer-only="true" min="60" max="140" increment="5" apply-on-change="true"/>
-                <slider-setting text="Heart Rate Upper Bound" show-buttons="true" value="HRHigh" integer-only="true" min="140" max="220" increment="5" apply-on-change="true"/>
+                <slider-setting text="Heart Rate Lower Bound" show-buttons="true" value="HRLow" integer-only="true" min="50" max="140" increment="5" apply-on-change="true"/>
+                <slider-setting text="Heart Rate Upper Bound" show-buttons="true" value="HRHigh" integer-only="true" min="110" max="220" increment="5" apply-on-change="true"/>
                 <horizontal pad-top="1" pad-bottom="1">
@@ -29,3 +29,3 @@
                 <bool-setting text="Auto Pause" value="AutoPause" hover-hint="Automatically pause the game if your heart rate is too high, set threshold below" apply-on-change="true"/>
-                <slider-setting text="Pause Heart Rate" show-buttons="true" value="PauseHR" integer-only="true" min="150" max="250" increment="5" apply-on-change="true"/>
+                <slider-setting text="Pause Heart Rate" show-buttons="true" value="PauseHR" integer-only="true" min="110" max="250" increment="5" apply-on-change="true"/>
             </vertical>
```

**Comment by qe201020335** [comment]
Added the change in 56aa5c2

Here is a build, see if the new bounds fit your use case
[HRCounter-2.1.0-bs1.21.0-56aa5c2.zip](https://github.com/qe201020335/HRCounter/files/8550340/HRCounter-2.1.0-bs1.21.0-56aa5c2.zip)

**Comment by qe201020335** [comment]
@xedlock please check if the new bounds fit your use case.

I will keep this change in all future releases if you think it is good.
