### ISSUE TITLE
Ingame Icon

### ISSUE THREAD

**Issue by SmokyJoe0** [qe201020335/HRCounter#33]
Is it possible to display a blood drop icon instead of the heart?
Because I use the plugin to monitor my blood sugar in the game.
👍

**Comment by qe201020335** [comment]
hmmm I'm guessing you are using a compatible data source that sends blood sugar as the heart rate field.
I could implement a feature for changing the icon but it will take a while because currently, the entire counter is from a unity asset bundle

**Comment by SmokyJoe0** [comment]
Yes, I'm using a compatible data source to send blood glucose as a heart rate field.
A function to change the icon would be perfect. Many thanks for the answer.

**Comment by qe201020335** [comment]
Sorry for not having anything for this long. There is a rewrite happening for easier future updates and will definitely add the support after the rewrite

**Comment by SmokyJoe0** [comment]
That sounds very good. Thanks for the feedback.

**Comment by qe201020335** [comment]
- [ ] Learn how to load image files at game runtime 😁 
- [ ] Make the in-game UI for icon selection

**Comment by qe201020335** [comment]
![preview](https://github.com/user-attachments/assets/6c7dea50-d6c8-4cfa-98ba-3b267dc5744b)

**Comment by qe201020335** [comment]
Implemented in #70 
Here is a build, tested with 1.37.3
[HRCounter-3.0.0-4-bs1.29.1-0ce2b8e.zip](https://github.com/user-attachments/files/16827520/HRCounter-3.0.0-4-bs1.29.1-0ce2b8e.zip)

**Comment by SmokyJoe0** [comment]
Seems like I need to update to 1.37.3, my 1.29.1 says no. ^^
But I think it's my game that's flawed.

**Comment by qe201020335** [comment]
I remember I did backport it to 1.29.1.
Let me double check and make a new build

**Comment by SmokyJoe0** [comment]
Ok, now we're talking ^^ It works! Thx man ^^
