### ISSUE TITLE
HRCounter not showing up in game

### ISSUE THREAD

**Issue by Serane-n** [qe201020335/HRCounter#40]
installed all requirements off MA and counters+ off github and can edit position of counter in counters+ config, but can't see ingame for whatever reason
tried changing position, reinstalling mod, changing counter position, and even tried the session id with the link in it as well and none worked
logs:
[2023.01.29.11.57.36.log](https://github.com/qe201020335/HRCounter/files/10530355/2023.01.29.11.57.36.log)
[2023.01.29.11.50.55.log.gz](https://github.com/qe201020335/HRCounter/files/10530356/2023.01.29.11.50.55.log.gz)
[_latest.log](https://github.com/qe201020335/HRCounter/files/10530359/_latest.log)

config:
{
  "ModEnable": true,
  "LogHR": false,
  "DataSource": "HypeRate",
  "PulsoidToken": "NotSet",
  "HypeRateSessionID": "728F",
  "PulsoidWidgetID": "NotSet",
  "FitbitWebSocket": "ws://localhost:8080/",
  "FeedLink": "NotSet",
  "NoBloom": true,
  "Colorize": true,
  "HideDuringReplay": true,
  "HRLow": 120,
  "HRHigh": 180,
  "LowColor": "#00FF00",
  "MidColor": "#FFFF00",
  "HighColor": "#FF0000",
  "PauseHR": 200,
  "AutoPause": false,
  "IgnoreCountersPlus": false,
  "DebugSpam": false,
  "StaticCounterPosition": {
    "x": 0.0,
    "y": 1.2,
    "z": 7.0
  }
}

**Comment by qe201020335** [comment]
Are you using the latest version of the mod?

I will also try to reproduce this myself. Thank you for reporting

**Comment by Serane-n** [comment]
i am using the latest release listed on github

**Comment by qe201020335** [comment]
Yeah I just got a repro as well. My bad, I will fix it asap 😞

**Comment by Serane-n** [comment]
alright, thank you!

**Comment by qe201020335** [comment]
[Debug.zip](https://github.com/qe201020335/HRCounter/files/10530606/Debug.zip)
Here is a quick fix you can test

**Comment by Serane-n** [comment]
just tried it, works perfect! thank you.
