### ISSUE TITLE
Implement OSC Server for common VRChat HR OSCs

### ISSUE THREAD

**Issue by 200Tigersbloxed** [qe201020335/HRCounter#43]
Currently, there's a high demand for OSC software for VRChat, adding extensibility to people's avatars. One of the extended features are adding HRCounters on avatars. Because of this, there have been numerous OSC applications created to receive HR data and send it to VRChat via. OSC. Some examples listed below

+ [HRtoVRChat](https://github.com/200Tigersbloxed/HRtoVRChat_OSC)
+ [VRCOSC](https://github.com/VolcanicArts/VRCOSC)
+ [vrc-osc-miband-hrm](https://github.com/vard88508/vrc-osc-miband-hrm)

Having an OSC server (with something like [SharpOSC](https://github.com/Reimajo/SharpOSC)) to read from endpoints and extract data from these OSC clients (for example, `/avatar/HR` with HRtoVRChat) would extend device support greatly, and allow for an easy to implement custom HR Interface without a developer having to implement it themselves in the main code to support HRCounter.

This shouldn't rule out the possibility of HRCounter having it's own SDK to dynamically load managed assemblies, but act as a compatibility layer for pre-existing VRChat OSC applications meant to send data to VRChat's OSC server.

**Comment by qe201020335** [comment]
Will very possibly make an external data source mod with all the dependencies merged so the base mod won't become too bloated

**Comment by qe201020335** [comment]
![image](https://github.com/qe201020335/HRCounter/assets/31044781/70fdb99b-d717-41b9-b732-419bd27fe098)
