### ISSUE TITLE
Black screen when loading level on 1.35.0

### ISSUE THREAD

**Issue by Happyllama25** [qe201020335/HRCounter#56]
Hey there!
Logs are attached, I ran all dependencies beforehand and tested functional until loading HRCounter, I do see it populates the .json with extra settings, and I also see the "Heart Rate" when I select the Counters+ mod in-game.
When I load the game, select a level, and press play, screen fades to black and doesn't come back, don't see my sabers/controllers or hear any audio, seems to stay in that state, longest test was about 6 minutes before I gave up and looked at the logs, not too sure what the error is.

[_latest.log](https://github.com/qe201020335/HRCounter/files/14808380/_latest.log)

Edit: Using Hyperate and a Quest 3, tested through SteamLink and Virtual Desktop

**Comment by qe201020335** [comment]
Thanks for the report! 
I am busy with my final exams at the moment (sadly). I will take a look and see if it is an easy fix. If not, I will be free and start working on mods in two weeks.

**Comment by qe201020335** [comment]
Oh I see you are using the stable release for older versions of the game. Can you try using this pre-release? The pre-release is tested on game version 1.34.2, but i have not tested it on 1.35.0.
 https://github.com/qe201020335/HRCounter/releases/tag/3.0.0-2
You can simply unzip and overwrite exsiting files, and don't worry about the config.

**Comment by Happyllama25** [comment]
Doesn't work, same problem, although this time I do see HRCounter in the mod menu on the left side, and I can enter and configure options, still black when loading.

Log seems the same, attached and trimmed in the middle for size.
[_latest.log](https://github.com/qe201020335/HRCounter/files/14808638/_latest.log)

If you cannot fix it just yet no pressure!

**Comment by qe201020335** [comment]
I kind of want to wait for the mods to be available for 1.36.0 and then directly update the mod to support that. In the mean time I will continue my rewrite and refactor

**Comment by Happyllama25** [comment]
Yep, understandable, I've been using it on the downgraded legacy version just fine.

**Comment by qe201020335** [comment]
@Happyllama25 Here is a quick fixed version for 1.36.0, should also work on 1.35 but i didn't test
[HRCounter-3.0.0-2-bs1.36.0-7d9d1db.zip](https://github.com/qe201020335/HRCounter/files/15105833/HRCounter-3.0.0-2-bs1.36.0-7d9d1db.zip)
