### ISSUE TITLE
HR Counter not appearing in levels

### ISSUE THREAD

**Issue by herglotzmarco** [qe201020335/HRCounter#9]
Hey,

I think this issue https://github.com/qe201020335/HRCounter/issues/7 actually still persists in the current version. I can configure the counter, but it refuses to work in the levels.

I think the issue is a missing dependency however. The Beat Saber logs states that websocket-sharp is missing. Probably the easiest fix is to add this to the required mods section of the installation guide ^^

> [CRITICAL @ 21:46:16 | SiraUtil] System.TypeLoadException: Could not load type of field 'HRCounter.Data.HypeRate:_webSocket' (6) due to: Could not load file or assembly 'websocket-sharp, Version=1.0.2.1803, Culture=neutral, PublicKeyToken=5660b08a1845a91e' or one of its dependencies. assembly:websocket-sharp, Version=1.0.2.1803, Culture=neutral, PublicKeyToken=5660b08a1845a91e type:<unknown type> member:(null) signature:<none>
> [CRITICAL @ 21:46:16 | SiraUtil]   at HRCounter.HRCounter.CounterInit () [0x00024] in <058d33a233044f7692f5b438d1c18b19>:0 
> [CRITICAL @ 21:46:16 | SiraUtil]   at CountersPlus.Counters.Event_Broadcasters.CounterEventBroadcaster.Initialize () [0x00015] in <85e7d6fc15a141cb8afa3ea6afdf8fc6>:0 
> [CRITICAL @ 21:46:16 | SiraUtil]   at (wrapper dynamic-method) Zenject.InitializableManager.DMD<Zenject.InitializableManager::Initialize>(Zenject.InitializableManager)

Edit: Installing websocket-sharp in the version currently available on ModAssistant indeed fixes the issue

**Comment by qe201020335** [comment]
Thanks for finding this, will add the dependency
